#!/usr/bin/expect -f
#
# Brings up MTS system from initial IPL
# 
 
log_user 1               ;# if you want to see what it does
spawn c3270 localhost:3270
set timeout 120
set initialcount 0
set tmoutcnt 0
while { 1 } {
   expect {
      "current system (yes or no)?"               { set which firstipl }
      "otherwise re-IPL now."                     { set which needok }
      "Enter initials and reason for reloading:"  { set which needinitial }
      "Post-IPL system successfully loaded."      { set which needcancel }
      "PEEK initialization complete"              { set which loadhasp }
      "Job name is too long"                      { set which loadhasp }
      "Enter HASP requests"                       { set which starthasp }
      "MTS HASP START (17 January 2012)"          { set which startlas }
      "Telnet (TLNT) connections."                { set which releaseex }
      timeout                                     { incr tmoutcnt }
   }

   if { $which == "firstipl" } {
      sleep 1;
      send "yes";
      send "\015"
   }
   if { $which == "needok"} {
      sleep 1;
      send "OK";
      send "\015"
   }
   if { $which == "needinitial" } {
      if { $initialcount == 0 } {
         set initialcount 1;
         sleep 1;
         send "SH";
         send "\015"
      }
   }
   if { $which == "needcancel" } {
      sleep 1;
      send "\001";
      send "2"
   }
   if { $which == "loadhasp" } {
      sleep 2;
      send "hasp";
      send "\015"
   }
   if { $which == "starthasp" } {
      sleep 1;
      send "mts *hsp";
      send "\015"
   }
   if { $which == "startlas" } {
      sleep 1;
      send "mts *las";
      send "\015"
   }
   if { $which == "releaseex" } {
      sleep 1;
      send "\$release ex";
      send "\015"
      break
   }
   if { $tmoutcnt > 10 } {
      send_user "Didn't get to release ex point\n"
      exit
   }
}
expect "c3270>" { sleep 1; send "quit\n"; }
